source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem "mongoid", "~> 2.4"
gem 'bson_ext'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

# gem 'therubyracer'

# gem 'jquery-rails'
gem 'cloudfoundry-jquery-rails'

gem 'sorcery'

gem 'carrierwave-mongoid'

gem "kaminari"